name: mundose-pin1

services:
  jenkins:
    image: docker.io/mguazzardo/pipe-seg
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_data:/var/jenkins_home
      - ./:/app
    networks:
      - jenkins-network

  registry:
    image: registry:2
    ports:
      - "5000:5000"
    networks:
      - jenkins-network

volumes:
  jenkins_data:

networks:
  jenkins-network:
