apiVersion: v1
kind: Service
metadata:
  labels:
    app: testapp
  name: testapp
  namespace: default
spec:
  ports:
  - nodePort: 30080
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: testapp
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
